[phases.setup]
nixPkgs = ["nodejs_18", "chromium"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @palbase/shared build",
  "pnpm --filter @palbase/scraper build"
]

[start]
cmd = "node packages/scraper/dist/index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "chromium"
