[phases.setup]
nixPkgs = ["nodejs_18", "chromium", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = [
  "pnpm --filter @palbase/shared build",
  "pnpm --filter @palbase/scraper build"
]

[start]
cmd = "node packages/scraper/dist/index.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chromium/bin/chromium"
